server:
    port: 8081

spring:
    application:
        name: api-gateway
    main:
        web-application-type: reactive
    cloud:
        gateway:
            routes:
                - id:
                  uri: lb://USER-SERVICE
                  predicates:
                    - Path=/users/**
                - id: twitch-client-service
                  uri: lb://TWITCH-CLIENT-SERVICE
                  predicates:
                    - Path=/twitch/**

        discovery:
            client:
                service-url:
                    default-zone: http://localhost:8761/eureka/

    management:
        endpoints:
            web:
                exposure:
                    include: health, metrics, info, loggers