# Utilise l'image officielle PostgreSQL comme base
FROM postgres:latest

# Expose le port PostgreSQL (utile si vous voulez documenter)
EXPOSE 5432

# Définit des variables d'environnement par défaut (peuvent être remplacées lors de l'exécution)
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=mypassword
ENV POSTGRES_DB=user-database
